---
title: "Approximation de Schmidt"
author: "AMEKOE Kodjo Mawuena"
date: "07/07/2020"
output: html_document
---

```{r}
# Fonction approximation de schmidt
function_schmidtNew = function(alpha, beta){
  expOfalphaXbeta  = exp(alpha*beta)
  (1/alpha)*(log(1+expOfalphaXbeta)+log(1+(1/expOfalphaXbeta)))
}

# visualisation avec la fonction plot de R 

# graphe (a)
#png("approx_sch_1.png")
# png pour exporter la figure en format .png
x1 = seq(-0.2,0.2, length.out = 50)
plot(x1,abs(x1),col= 1,type = 'l',
     main = "Pour un vecteur [-0.2,0.2]",
     ylab = expression("|X|"),
     xlab = expression("X")
     )
points(x1,function_schmidtNew(10,x1),col = 2)
points(x1,function_schmidtNew(25,x1),col = 3)
points(x1,function_schmidtNew(100,x1),col = 4)
legend("topright",
       c("réel", "alpha = 10","alpha = 65","alpha= 100"),
       lty=1:1,
       col=c(1, 2,3,4)
       )

# graphe(b)


#png("approx_sch_2.png")
x2 = seq(-1,1, length.out = 50)
plot(x2,abs(x2),col= 1,type = 'l',
     main = "Pour un vecteur [-1,1]",
     ylab = expression("|X|"),
     xlab = expression("X")
     )
points(x2,function_schmidtNew(10,x2),col = 2)
points(x2,function_schmidtNew(25,x2),col = 3)
points(x2,function_schmidtNew(100,x2),col = 4)
legend("topright",
       c("réel","alpha = 10","alpha = 65","alpha= 100"),
       lty=1:1,
       col=c(1, 2,3,4)
       )
```



```{r}


```

```{r}


```