---
title: 'Simulation  Figure de l''article : Elastic-net'
author: "AMEKOE Kodjo Mawuena"
date: "16/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list = ls())
cat("\014")
library(class)
library(ggplot2)
library(dplyr)
library(glmnet)
library(alocvBeta)
library(rmutil)
library(tictoc)
library(latex2exp)

# initialisation 
p_values         =     c(200, 1000, 10000)
n                =     1000
k                =     100
alpha_elnet      =     0.5
o                =     1  
m                =     30 #number of lambdas


set.seed(1)

eror             =     list() # sauvegarde des résultats sous forme d'une liste
time.lo          = rep(0 , length(p_values))
time.alo          = rep(0 , length(p_values))
time.fit         = rep(0 , length(p_values))


for (ind_p in 1:length(p_values) ){
p                = p_values[ind_p]
# le nombre maximal de coef à non nul
dfmax_           =     floor(min(p,n) * 0.7)
spikeCov         =     1 # Spiked(=1) 

if (spikeCov){
  # spike covariance
  a_             =    0.5 # correlation coeeficient
  row_           =    c(1:p, 1:p)
  column_        =    c(1:p, rep(p+1, p))
  elmts          =    c(rep(sqrt(1-a_), p),
                        rep(sqrt(a_), p)
                        )
  F_              =    sparseMatrix(i = row_,
                                    j = column_,
                                    x = elmts
                                    )
} else {
  a_               =     0.9 # Toeplitz AR(1) covariance
  F_                =    matrix(rep(0, p*p),
                                nrow = p,
                                ncol = p
                                )
  for (row_ in 1:p){
    for (column_ in 1:row_){
      F_[row_, column_]   =   a_^abs(row_ - column_)
    }
  }
  F_              =    t(F_) 
}
# to make sure the var(x^T * beta.star) = 1
F_              =    F_ / sqrt(sum(F_[1, ]^2) * k) 
#C   =    F_ %*% t(F_)
beta.star      =    rep(0, p)
iS             =    sample(1:p, k)
beta.star[iS]  =    rlaplace(k, m=0, s=1/sqrt(2))
X              =    F_ %*% matrix(rnorm( n*ncol(F_),
                                         mean = 0,
                                         sd = 1 
                                         ),
                                  nrow = ncol(F_), ncol = n
                                  )
X              =    t(X)
e              =    rnorm(n, mean = 0, sd = o)
y              =    X %*% beta.star + e
lambdaS        =    exp(seq(log(1/n), log(100/n), length.out = m))

ptm            =     proc.time()      
lo             =     cv.glmnet(X, y, alpha = alpha_elnet,
                               intercept = FALSE,
                               standardize = FALSE,
                               lambda = lambdaS,
                               nfolds = n
                               )
ptm            =     proc.time() - ptm
time.lo[ind_p]        =     ptm["elapsed"] 

ptm            =     proc.time() 
fit            =     glmnet(X, y,
                            alpha = alpha_elnet,
                            intercept = FALSE,
                            standardize = FALSE,
                            lambda = lambdaS
                            )
ptm            =     proc.time() - ptm
time.fit[ind_p]       =     ptm["elapsed"] 

ptm            =     proc.time()
alo            =     glmnetALO(X, y, glm_obj = fit,
                               alpha = alpha_elnet,
                               standardize = FALSE,
                               type.measure = "mse")
ptm            =     proc.time() - ptm
time.alo[ind_p]       =     time.fit[ind_p] + ptm["elapsed"] 

cat(sprintf("n = %s| p = %s \n", n, p))
cat(sprintf("TIME: lo = %.2f| alo = %.2f| fit =%.2f \n",
            time.lo[ind_p],
            time.alo[ind_p],
            time.fit[ind_p]
            )
    )
cat(sprintf(" df_max/p = %.3f \n", max(fit$df/p)))
cat(sprintf("-------------------------------------- \n"))

eror[[ind_p]]           =     data.frame( c(rep("LO", length(lo$lambda)),
                                            rep("ALO", length(alo$lambda)) 
                                            ), 
                                           n*c(lo$lambda, alo$lambda) ,
                                           c(lo$cvm, alo$alom),
                                           c(lo$cvsd,
                                             rep(0, length(alo$lambda))
                                             )
                                          )
colnames(eror[[ind_p]]) =     c("method", "lambda", "err", "se")


}

time_fig4_article    = data.frame(time.fit,time.alo,time.lo)

# sauvegarde des données :écriture dans un fichier txt
write.table(eror[[1]],"eror1_fig4_arcticle.txt", sep="\t" )
write.table(eror[[2]],"eror2_fig4_arcticle.txt", sep="\t" )
write.table(eror[[3]],"eror3_fig4_arcticle.txt", sep="\t" )
write.table(time_fig4_article,
            "time_fig4_article.txt",
            sep = "\t"
            )

# Pour la figre (a)
p = p_values[1]
eror1_fig4_arcticle = read.table("eror1_fig4_arcticle.txt")
time_fig4_article   = read.table("time_fig4_article.txt")
time.alo            = time_fig4_article$time.alo[1]
time.lo            = time_fig4_article$time.lo[1]
time.fit           = time_fig4_article$time.fit[1]

eror.plot      =     ggplot(eror1_fig4_arcticle,
                            aes(x=lambda, y = err, color=method)) +
                     geom_line(size=1)
eror.plot      =     eror.plot  + scale_x_log10()
eror.plot      =     eror.plot  + 
                     theme(legend.text = element_text(colour="black",
                                                      size=16,
                                                      face="bold",
                                                      family = "Courier"
                                                      )
                           )
eror.plot      =     eror.plot  + 
                     geom_pointrange(aes(ymin=err-se, ymax=err+se),
                                     size=0.8,
                                     shape=15
                                     )
eror.plot      =     eror.plot  + theme(legend.title=element_blank())
eror.plot      =     eror.plot  + 
                     scale_color_discrete(breaks=c("LO", "ALO"))
eror.plot      =     eror.plot  + 
                     theme( axis.title.x = element_text(size=24),
                            axis.text.x  = element_text(angle=0,
                                                        vjust=0.5,
                                                        size=14
                                                        ),
                            axis.text.y  = element_text(angle=0,
                                                        vjust=0.5,
                                                        size=14
                                                        )
                            )

eror.plot      =     eror.plot  + xlab( expression(paste( lambda))) +
                     ylab("")
eror.plot      =     eror.plot  + 
                     theme(plot.title = element_text(hjust = 0.5,
                                                     vjust = -32,
                                                     size=12,
                                              family = "Courier"
                                                     )
                           )
eror.plot      =     eror.plot  + 
                     ggtitle((sprintf("n=%s,
                                      p=%s
                                      \n\n LO:%0.2f(sec)
                                      \n ALO:%0.2f(sec) 
                                      \n FIT:%.2f(sec)",
                                      n,p,
                                      time.lo,
                                      time.alo,
                                      time.fit
                                      )
                              )
                             )


print(eror.plot)


# Pour la figure (b), il suffit de prendre le deuxième élément
# dans le code qui fait la figure (a)

# pour la figure (c), il faut prendre maintenant
# le troisième élément.
```






```{r}

```

```{r}
ggsave("eror1_fig4_arcticle.png",eror.plot)
```







```{r}
p = p_values[2]
eror2_fig4_arcticle = read.table("eror2_fig4_arcticle.txt")
time_fig4_article   = read.table("time_fig4_article.txt")
time.alo            = time_fig4_article$time.alo[2]
time.lo            = time_fig4_article$time.lo[2]
time.fit           = time_fig4_article$time.fit[2]

eror.plot      =     ggplot(eror2_fig4_arcticle, aes(x=lambda, y = err, color=method)) +   geom_line(size=1)
eror.plot      =     eror.plot  + scale_x_log10()#(breaks = c(seq(0.1,2.4,0.2)))
eror.plot      =     eror.plot  + theme(legend.text = element_text(colour="black", size=16, face="bold", family = "Courier"))
eror.plot      =     eror.plot  + geom_pointrange(aes(ymin=err-se, ymax=err+se),  size=0.8,  shape=15)
eror.plot      =     eror.plot  + theme(legend.title=element_blank())
eror.plot      =     eror.plot  + scale_color_discrete(breaks=c("LO", "ALO"))
eror.plot      =     eror.plot  + theme(axis.title.x = element_text(size=24),
                                        axis.text.x  = element_text(angle=0, vjust=0.5, size=14),
                                        axis.text.y  = element_text(angle=0, vjust=0.5, size=14))
#eror.plot      =     eror.plot  + theme(axis.title.y = element_text(size=16, face="bold", family = "Courier"))
eror.plot      =     eror.plot  + xlab( expression(paste( lambda))) + ylab("")
eror.plot      =     eror.plot  + theme(plot.title = element_text(hjust = 0.5, vjust = -32, size=12, family = "Courier"))
#eror.plot      =     eror.plot  + ggtitle(TeX(sprintf("$n$=%s,$p$=%s,$t_{LO}$=%s,$t_{ALO}$=%0.2f,$t_{FIT}$=%.2f",n,p,time.lo,time.alo,time.fit)))
eror.plot      =     eror.plot  + ggtitle((sprintf("n=%s, p=%s \n\n LO:%0.2f(sec) \n ALO:%0.2f(sec) \n FIT:%.2f(sec)",n,p,time.lo,time.alo,time.fit)))


print(eror.plot)
```
```{r}
ggsave("eror2_fig4_arcticle.png",eror.plot)
```



```{r}
p = p_values[3]
eror3_fig4_arcticle = read.table("eror3_fig4_arcticle.txt")
time_fig4_article   = read.table("time_fig4_article.txt")
time.alo            = time_fig4_article$time.alo[3]
time.lo            = time_fig4_article$time.lo[3]
time.fit           = time_fig4_article$time.fit[3]

eror.plot      =     ggplot(eror3_fig4_arcticle, aes(x=lambda, y = err, color=method)) +   geom_line(size=1)
eror.plot      =     eror.plot  + scale_x_log10()#(breaks = c(seq(0.1,2.4,0.2)))
eror.plot      =     eror.plot  + theme(legend.text = element_text(colour="black", size=16, face="bold", family = "Courier"))
eror.plot      =     eror.plot  + geom_pointrange(aes(ymin=err-se, ymax=err+se),  size=0.8,  shape=15)
eror.plot      =     eror.plot  + theme(legend.title=element_blank())
eror.plot      =     eror.plot  + scale_color_discrete(breaks=c("LO", "ALO"))
eror.plot      =     eror.plot  + theme(axis.title.x = element_text(size=24),
                                        axis.text.x  = element_text(angle=0, vjust=0.5, size=14),
                                        axis.text.y  = element_text(angle=0, vjust=0.5, size=14))
#eror.plot      =     eror.plot  + theme(axis.title.y = element_text(size=16, face="bold", family = "Courier"))
eror.plot      =     eror.plot  + xlab( expression(paste( lambda))) + ylab("")
eror.plot      =     eror.plot  + theme(plot.title = element_text(hjust = 0.5, vjust = -32, size=12, family = "Courier"))
#eror.plot      =     eror.plot  + ggtitle(TeX(sprintf("$n$=%s,$p$=%s,$t_{LO}$=%s,$t_{ALO}$=%0.2f,$t_{FIT}$=%.2f",n,p,time.lo,time.alo,time.fit)))
eror.plot      =     eror.plot  + ggtitle((sprintf("n=%s, p=%s \n\n LO:%0.2f(sec) \n ALO:%0.2f(sec) \n FIT:%.2f(sec)",n,p,time.lo,time.alo,time.fit)))


print(eror.plot)
```
```{r}
ggsave("eror3_fig4_arcticle.png",eror.plot)
```
